### ISSUE TITLE
Deploy Microservice

### ISSUE THREAD

**Issue by RakeshDevUK** [redhat-developer-demos/istio-tutorial#135]
Having a big challenge to deploy the first microservice customer , unable to execute the below command for sidecar
oc apply -f <(istioctl kube-inject -f ../../kubernetes/Deployment.yml) -n tutorial
Error :-1: 
**Error: could not read valid configmap "istio" from namespace  "istio-system": Get http://localhost:8080/api/v1/namespaces/istio-system/configmaps/istio: dial tcp [::1]:8080: connect: connection refused - Use --meshConfigFile or re-run kube-inject with `-i <istioSystemNamespace> and ensure valid MeshConfig exists**

Note :- everything is properly setup with istio and as i can see 16 pods running  , also istioctl is also setup in classpath

Can you someone please look into?

**Comment by lordofthejars** [comment]
I have just tried today and it worked. 
First of all which version of OpenShift, Minishiftstand Istio are you using?

**Comment by RakeshDevUK** [comment]
Openshfit 3.10 running on Centos machine
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8

Isito 1.0.2

Also i can see the istio config map file is present in istio-system namespace

**Comment by lordofthejars** [comment]
No idea, can you try Istio 1.0.0, it seems that there can be some problems in Istio 1.0.2 which has been fixed in minishift by using some hacky things but no idea in openshift directly.

**Comment by RakeshDevUK** [comment]
strange but with 1.0.0 is also same? why is it trying to pull the config file by local host http://localhost:8080/api/v1/namespaces/istio-system/configmaps/istio

[virgin@localhost openshift-origin-client-tools-v3.10.0-dd10d17-linux-64bit]$ sudo ./oc apply -f <(/home/virgin/Downloads/istio-1.0.0/bin/istioctl kube-inject -f /home/virgihttp://localhost:8080/api/v1/namespaces/istio-system/configmaps/istion/Downloads/istio-tutorial/customer/kubernetes/Deployment.yml) -n tutorial
Error: could not read valid configmap "istio" from namespace  "ishttp://localhost:8080/api/v1/namespaces/istio-system/configmaps/istiotio-system": Get http://localhost:8080/api/v1/namespaces/istio-system/configmaps/istio: dial tcp [::1]:8080: connect: connection refused - Use --meshConfigFile or re-run kube-inject with `-i <istioSystemNamespace> and ensure valid MeshConfig exists
[sudo] password for virgin: 
error: the path "/dev/fd/63" does not exist

**Comment by RakeshDevUK** [comment]
Tried installing the istio-system 16 pods via istio 1.0.0 but still the same error. will try 0.8

**Comment by RakeshDevUK** [comment]
tried installing with 1.0.0 based yaml files as well for the namespace istio-system but still the same error...;(

**Comment by rafabene** [comment]
I couldn't reproduce. Please reopen if the problem still persists.
