### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/istio-tutorial#182]
java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
~/tmp/istio-tutorial/recommendation/java/vertx $ java -jar target/recommendation.jar
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/Users/burrsutter/tmp/istio-tutorial/recommendation/java/vertx/target/recommendation.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Jan 05, 2019 7:03:07 PM io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer
INFO: Succeeded in deploying verticle

**Comment by burrsutter** [comment]
<vertx.version>3.6.2</vertx.version>

**Comment by rafabene** [comment]
Fixed at https://github.com/redhat-developer-demos/istio-tutorial/commit/c1a7076a150dab63aaa9fa988c5de331a02560dc

**Comment by ZinfinityDarshan** [comment]
still facing same issue with vertx 3.8.1

`WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.resolver.dns.DnsNameResolver (file:/C:/Users/Darshan/.m2/repository/io/netty/netty-resolver-dns/4.1.39.Final/netty-resolver-dns-4.1.39.Final.jar) to method sun.net.dns.ResolverConfiguration.open()
WARNING: Please consider reporting this to the maintainers of io.netty.resolver.dns.DnsNameResolver
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
HTTP server started on port 8888`
